name: _publish

on: 
  workflow_call:

jobs:
  publish:
    runs-on: ubuntu-latest
    container:
      image: joinself/tools
    steps:
      - name: Setup job
        uses: joinself/github-actions-public/setup-job@main
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: artifacts
      - name: Publish
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_CI_CI: ${{ secrets.SLACK_WEBHOOK_CI_CI }}
        run: |
          . ${GITHUB_WORKSPACE}/.ci/env
          chown root:root .

          apt-get update
          apt-get install -y tree
          ls -lah
          tree
          exit 1

          git config --global user.name ci
          git config --global user.email ops@joinself.com

          branch=$(git branch --show-current)
          tags=$(git tag --merged ${branch} | sort -V)
          commit_message=$(git show -s --format=%s)
          if [[ "${tags}" == "" ]]; then
            version="0.1.0"
          else
            current_version=$(echo "${tags}" | tail -n 1)
            case $commit_message in
              *\[bump-major\]*)
                version=$(semver bump major $current_version)
                ;;
              *\[bump-patch\]*)
                version=$(semver bump patch $current_version)
                ;;
              *)
                version=$(semver bump minor $current_version)
                ;;
            esac
          fi

          git tag -a ${version} -m "${version}"
          git push origin ${version}

          subject=$(git log -n 1 --format=%s)
          body=$(git log -n 1 --format=%b | grep -E '^\*|^-' | sed 's/^*/-/g') || true
          if [[ -z ${body} ]]; then
            release_notes="- ${subject}"
          else
            release_notes="${body}"
          fi

          fpm -s dir -t deb -n self-omemo -v ${version} -a arm64 ./self-omemo-aarch64-unknown-linux-gnu/libself_omemo.a=/usr/lib/ ./self-omemo-aarch64-unknown-linux-gnu/self_omemo.h=/usr/include/
          fpm -s dir -t deb -n self-omemo -v ${version} -a amd64 ./self-omemo-x86_64-unknown-linux-gnu/libself_omemo.a=/usr/lib/ ./self-omemo-x86_64-unknown-linux-gnu/self_omemo.h=/usr/include/

          fpm -s dir -t rpm -n self-omemo -v ${version} -a aarch64 ./self-omemo-aarch64-unknown-linux-gnu/libself_omemo.a=/usr/lib/ ./self-omemo-aarch64-unknown-linux-gnu/self_omemo.h=/usr/include/
          fpm -s dir -t rpm -n self-omemo -v ${version} -a x86_64 ./self-omemo-x86_64-unknown-linux-gnu/libself_omemo.a=/usr/lib/ ./self-omemo-x86_64-unknown-linux-gnu/self_omemo.h=/usr/include/

          mv self-omemo-aarch64-unknown-linux-gnu self-omemo-aarch64-unknown-linux-gnu-${version}
          mv self-omemo-x86_64-unknown-linux-gnu self-omemo-x86_64-unknown-linux-gnu-${version}
          mv self-omemo-aarch64-linux-android self-omemo-aarch64-linux-android-${version}
          mv self-omemo-armv7-linux-androideabi self-omemo-armv7-linux-androideabi-${version}
          mv self-omemo-i686-linux-android self-omemo-i686-linux-android-${version}
          mv self-omemo-x86_64-linux-android self-omemo-x86_64-linux-android-${version}

          tar -czvf self-omemo-aarch64-unknown-linux-gnu-${version}.tar.gz self-omemo-aarch64-unknown-linux-gnu-${version}
          tar -czvf self-omemo-x86_64-unknown-linux-gnu-${version}.tar.gz self-omemo-x86_64-unknown-linux-gnu-${version}
          tar -czvf self-omemo-aarch64-linux-android-${version}.tar.gz self-omemo-aarch64-linux-android-${version}
          tar -czvf self-omemo-armv7-linux-androideabi-${version}.tar.gz self-omemo-armv7-linux-androideabi-${version}
          tar -czvf self-omemo-i686-linux-android-${version}.tar.gz self-omemo-i686-linux-android-${version}
          tar -czvf self-omemo-x86_64-linux-android-${version}.tar.gz self-omemo-x86_64-linux-android-${version}

          gh release create "${version}" --notes "${release_notes}" self-omemo_${version}_arm64.deb self-omemo_${version}_amd64.deb self-omemo-${version}-1.aarch64.rpm self-omemo-${version}-1.x86_64.rpm self-omemo-aarch64-unknown-linux-gnu-${version}.tar.gz self-omemo-x86_64-unknown-linux-gnu-${version}.tar.gz self-omemo-aarch64-linux-android-${version}.tar.gz self-omemo-armv7-linux-androideabi-${version}.tar.gz self-omemo-i686-linux-android-${version}.tar.gz self-omemo-x86_64-linux-android-${version}.tar.gz

          slack-release-notification -v ${version}
      - name: Failure notification
        if: ${{ failure() }}
        uses: joinself/github-actions-public/failure-notification@main
        with:
          slack-webhook: ${{ secrets.SLACK_WEBHOOK_CI_ALERTS }}
